# Generated by Django 4.2.6 on 2023-10-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                (
                    "jobRole",
                    models.CharField(
                        choices=[
                            ("librarian", "Librarian"),
                            ("counselor", "Guidance Counselor"),
                            ("nurse", "School Nurse"),
                            ("coach", "Coach"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
