# Generated by Django 4.2.6 on 2023-10-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Teacher", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="qualifications",
            field=models.CharField(
                choices=[
                    (1, "Doctorate"),
                    (2, "Masters"),
                    (3, "Degree"),
                    (4, "Diploma"),
                    (5, "Certificate"),
                ],
                max_length=50,
            ),
        ),
    ]
