# Generated by Django 4.2.6 on 2023-10-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Teacher", "0004_alter_teacher_qualifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="qualifications",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Doctrate"),
                    (2, "Masters"),
                    (3, "Degree"),
                    (4, "Diploma"),
                    (5, "Certificate"),
                ],
                null=True,
            ),
        ),
    ]
