# Generated by Django 4.2.6 on 2023-10-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Teacher", "0005_alter_teacher_qualifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="qualifications",
            field=models.CharField(
                blank=True,
                choices=[
                    ("doctrate", "Doctrate"),
                    ("masters", "Masters"),
                    ("degree", "Degree"),
                    ("diploma", "Diploma"),
                    ("certificate", "Certificate"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
