# Generated by Django 4.2.6 on 2023-10-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("author_first_name", models.CharField(max_length=50)),
                ("author_last_name", models.CharField(max_length=50)),
                (
                    "availabilityStatus",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            ("available", "Available"),
                            ("checked_out", "Checked Out"),
                            ("reserved", "Reserved"),
                            ("lost", "Lost"),
                            ("damaged", "Damaged"),
                        ],
                        null=True,
                    ),
                ),
            ],
        ),
    ]
