# Generated by Django 4.2.4 on 2023-10-23 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Attendance", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="attendaceStatus",
            new_name="attendanceStatus",
        ),
    ]
