# Generated by Django 4.2.6 on 2023-10-24 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Employees", "0001_initial"),
        ("Teacher", "0006_alter_teacher_qualifications"),
        ("Attendance", "0002_rename_attendacestatus_attendance_attendancestatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Teacher.teacher",
            ),
        ),
    ]
