# Generated by Django 4.2.6 on 2023-10-25 06:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Attendance", "0004_alter_attendance_employee_alter_attendance_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="teacher",
        ),
    ]
